name: Extract RTS Info Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes (UTC time)
  workflow_dispatch:  # allows manual trigger

jobs:
  extract-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Install dependencies2
        run: npm ci

      - name: Download RTS info page
        run: |
          echo "get rts.ch/info page"
          wget https://www.rts.ch/info -O input.html

      - name: Extract card titles from page
        run: |
          echo "extract card titles from page"
          node extract.js

      - name: Extract daily removals into removed-by-day folder
        run: |
          echo "extractDayliRemoval into folder removed-by-day"
          node extractDayliRemoval.js

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: html-output
          path: html/
      - name: Commit and push updated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add html card-titles.json removed-by-day || true
          git diff --cached --quiet || git commit -m "Update card titles and reports [auto]"

          # Use token-authenticated push
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
